
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
    PATCH_SIZE: 4
    MLP_RATIO: 4.0
    QKV_BIAS: True
    DROP_RATE: 0.0
    ATTN_DROP_RATE: 0.0
    USE_CHECKPOINT: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    SWIN_PRETRAINED_WEIGHTS: 'swin_base_patch4_window12_384_22k.pth'
  WEIGHTS: ""
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  META_ARCHITECTURE: "GRES"
  SEM_SEG_HEAD:
    NAME: "ReferringHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 80
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: [ "res3", "res4", "res5" ]
    DEFORMABLE_TRANSFORMER_ENCODER_N_POINTS: 4
    DEFORMABLE_TRANSFORMER_ENCODER_N_HEADS: 8
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedReferringDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    LANG_ATT_WEIGHT: 0.1
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8 # transformer config
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
      SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: False

INPUT:
  IMAGE_SIZE: 480
  DATASET_MAPPER_NAME: "refcoco"
  MIN_SCALE: 0.75
  MAX_SCALE: 1.0
  FORMAT: "RGB"
  SIZE_DIVISIBILITY: -1
  COLOR_AUG_SSD: False
  CROP:
    SINGLE_CATEGORY_MAX_AREA: 1.0

DATASETS:
  DATASET_NAME: 'grefcoco'
  SPLIT_BY: "unc"
  REF_ROOT: "/data/zqc/datasets/ref"
  TRAIN: ("grefcoco_unc_train",)
  TEST: ("grefcoco_unc_val",)
REFERRING:
  BERT_TYPE: "/data/zqc/huggingface-models/bert-base-uncased"
  MAX_TOKENS: 20
SOLVER:
  GPU: 8
  BATCH_SIZE: 24
  NUM_WORKER: 8
  WORLD_SIZE: 1
  BASE_LR: 0.00001
  BASE_LR_END: 0.0000001
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_EMBED: 0.0
  WEIGHT_DECAY_NORM: 0.0
  MOMENTUM: 0.9
  STEPS: (110000, 140000)
  MAX_ITER: 150000
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
TEST:
  DETECTIONS_PER_IMAGE: 100